trigger:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '8e9969b3-7574-441c-a10f-7114dc3314f7'
  
  # Web app name
  webAppName: 'dev-beis-tp-db-publicsearch-portal'
  
  # Environment name
  environmentName: 'dev-beis-tp-db-publicsearch-portal'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps: # Checking out connected repo    
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
          npm run build --if-present
        displayName: 'npm install'

      - script: |
          # npm pack
        displayName: 'Package for release'

      - bash: | # Grab the package version
          v=`node -p "const p = require('./package.json'); p.version;"`
          echo "##vso[task.setvariable variable=packageVersion]$v"

      - task: CopyFiles@2
        inputs:
            contents: '*.tgz'
            targetFolder: $(Build.ArtifactStagingDirectory)/npm
        displayName: 'Copy archives to artifacts staging directory'

      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)'
          contents: 'package.json' 
          targetFolder: $(Build.ArtifactStagingDirectory)/npm
        displayName: 'Copy package.json'

      - task: PublishBuildArtifacts@1 
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)/npm'
          artifactName: npm
        displayName: 'Publish npm artifact'
